### ISSUE TITLE
Несколько небольших недочетов

### ISSUE THREAD

**Issue by jovfer** [AlenaErsh/C-2#1]
- [x] В репозитории лежат два проекта, нужно посмотреть какой из них более свежий и выкинуть другой. 
- [x] Не хватает .gitignore файла, добавьте и почистите тот мусор, который попал в гит (этот пункт актуален и для первой задачи тоже).
- [x] Надо доделать разбиение на файлы как в третьей задаче.

**Comment by AlenaErsh** [comment]
Все недочеты подправлены.

**Comment by jovfer** [comment]
@AlenaErsh игнорируемые файлы остались в гите.
вот тут несколько логичных ответов на тему чистки репозитория, если гитигнор был добавлен не сразу: https://stackoverflow.com/questions/7527982/applying-gitignore-to-committed-files

**Comment by AlenaErsh** [comment]
Теперь, наконец, вроде бы, всё))
